import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { getEnv } from "@/server/env";
import { ValidationError } from "@/server/errors";

/**
 * File storage behind a small interface so S3/GCS can replace the local disk later.
 * Files live outside public/ under STORAGE_DIR/<gymId>/<kind>/<uuid>.<ext> and are served
 * only through an authenticated, tenant-checked route handler.
 */
export interface StorageProvider {
  put(key: string, bytes: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

class LocalDiskStorage implements StorageProvider {
  constructor(private readonly root: string) {}

  private resolve(key: string) {
    const full = path.resolve(this.root, key);
    // Keys are generated by us, but never let one escape the storage root.
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }

  async put(key: string, bytes: Buffer) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, bytes, { flag: "wx" });
  }

  get(key: string) {
    return readFile(this.resolve(key));
  }

  async remove(key: string) {
    await rm(this.resolve(key), { force: true });
  }
}

let provider: StorageProvider | undefined;
export function getStorage(): StorageProvider {
  provider ??= new LocalDiskStorage(path.resolve(getEnv().STORAGE_DIR));
  return provider;
}

// ─────────────────────────── Upload validation ───────────────────────────

export const IMAGE_TYPES = {
  "image/jpeg": { ext: "jpg", magic: (b: Buffer) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
  "image/png": { ext: "png", magic: (b: Buffer) => b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) },
  "image/webp": { ext: "webp", magic: (b: Buffer) => b.subarray(0, 4).toString("latin1") === "RIFF" && b.subarray(8, 12).toString("latin1") === "WEBP" },
} as const;

export type ImageType = keyof typeof IMAGE_TYPES;
export const MAX_IMAGE_BYTES = 2 * 1024 * 1024;

/**
 * Detect the real type from the file's bytes (the browser-supplied type and file name are
 * not trusted), enforce the size limit, and return what to store.
 */
export function inspectImage(bytes: Buffer): { mimeType: ImageType; ext: string; sha256: string } {
  if (bytes.length === 0) throw new ValidationError("The file is empty.", { file: ["The file is empty."] });
  if (bytes.length > MAX_IMAGE_BYTES) throw new ValidationError("Images must be 2 MB or smaller.", { file: ["Images must be 2 MB or smaller."] });
  const match = (Object.entries(IMAGE_TYPES) as [ImageType, (typeof IMAGE_TYPES)[ImageType]][]).find(([, t]) => t.magic(bytes));
  if (!match) throw new ValidationError("Upload a JPEG, PNG or WebP image.", { file: ["Upload a JPEG, PNG or WebP image."] });
  return { mimeType: match[0], ext: match[1].ext, sha256: createHash("sha256").update(bytes).digest("hex") };
}

export function storageKey(gymId: string, kind: "member-photo" | "gym-logo", ext: string) {
  return `${gymId}/${kind}/${randomUUID()}.${ext}`;
}
